# -*- coding: utf-8 -*-
"""CIT312 Final Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1svCxEFfXxgU8WN7SiFP5-TkilasO6DsE
"""

# this code allows you to upload the input file to the colab cloud
# run this cell and select the file you want to upload to the colab cloud
from google.colab import files
uploaded = files.upload()

import matplotlib.pyplot as plt

def option1(popList):
  print("This is option 1")
  year = int(input('Enter the value: '))
  while year > 1990 or year < 1950:
    print('Error: input is incorrect.')
    year = int(input('Enter a valid value: '))
  print(f'The population in year {year}: {popList[year-1950]:,}')

def option2(popList):
  print("This is option 2")
  year1 = int(input('Enter the first year: '))
  year2 = int(input('Enter the second year: '))
  while year1 > 1990 or year1 < 1950 or year2 > 1990 or year2 < 1950:
    print('Error: input is incorrect.')
    year1 = int(input('Enter the valid first year: '))
    year2 = int(input('Enter the valid second year: '))
  difference = popList[year2-1950] - popList[year1-1950]
  print(f'The change in population between the two years is: {difference:,}')

def option3(popList):
    start = int(input("Enter first Year: ")) - 1950
    end = int(input("Enter second Year: ")) - 1950
    while start > 40 or start < 0 or end > 40 or end < 0:
      print('Error: input is incorrect.')
      start = int(input('Enter the valid first year: ')) - 1950
      end = int(input('Enter the valid second year: ')) - 1950
    total = 0
    for i in range(start,end+1):
        total += popList[i]
    average = total/((end+1)-start)
    print(f"The average is: {average:,.2f}")

def main():
  toContinue=True #this boolean controls the loop
  popList=[] #use this variable for the list of population values
  
  file = open("USPopulation1.txt",'r')
  for line in file:
    popList.append(int(line) * 1000)
  file.close()
  # Open and read in file USPopulation.txt. Convert the values to int, and multiply
  # by 1000 to expand to full amount.

  while toContinue:
    #display the menu
    print()
    print("Select one of the following options: ")
    print("1 - Display population for selected year")
    print("2 - Display change in population between two values")
    print("3 - Display the average population for range between two values")
    print("6 - Exit")

    choice = input("Select an option: ")

    if choice==str(1):
      option1(popList)
    elif choice==str(2):
      option2(popList)
    elif choice==str(3):
      option3(popList)
    elif choice==str(6):
      print("Program is exiting")
      toContinue=False

main()